# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ATMBank' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ATMBank
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'Kingfisher'
  pod 'IQKeyboardManagerSwift'
  pod 'ReachabilitySwift'
  pod 'RxDataSources'
  pod 'Moya'
  
  target 'ATMBankTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ATMBankUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
